name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: fastlane/github-actions/fastlane-env-reminder@latest
    - name: Bundle install
      run: bundle install
    - name: Run test
      run: bundle exec fastlane test
